# Generated by Django 3.2.9 on 2021-12-04 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20211204_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='about_blog',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='О блоге'),
        ),
    ]
