# Generated by Django 3.2.9 on 2021-12-04 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_user_about_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tittle',
            field=models.CharField(default=0, max_length=100, verbose_name='Название блога'),
            preserve_default=False,
        ),
    ]
