# Generated by Django 3.2.9 on 2021-12-07 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_viewed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewed',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Viewed', to='posts.post', verbose_name='Пост'),
        ),
    ]
